var json = '{\
"AMUS%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"AMUSEMENT%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"BLITH%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"CAREFRE%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"CELEBRAT%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"CHEER%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"CHEERFUL%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"CHEERY%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"CHUCKL%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"DELIGHT%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"DELIGHTFUL%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"ELAT%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"ENJOY%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"ENJOYABL%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"ENJOYMENT%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"ENTERTAIN%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"ENTERTAINMENT%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"ENTHUSIASM%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"ENTHUSIASTIC%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"EXCIT%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"EXHILERAT%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"EXULT%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"EXULTANT%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"FUN" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"FUNNY%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"GAIETY%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"GAY%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"GLAD%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"GLADNES%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"GLEE" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"GLEEFUL%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"GLEELY" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"GRATIFI%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"GRATIFY%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"GRIN%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"HAPPINES%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"HAPPY%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"HILARIOU%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"HUMOR%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"HUMOROU%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"HUMOUR%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"HUMOUROU%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"JOCUND%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"JOK%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"JOLLY" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"JOVIAL%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"JOY%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"JOYFUL%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"JOYOU%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"LAUGH%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"LAUGHTER%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"MERRIMENT%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"MERRY%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"MIRTH%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"MIRTHFUL%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"OVERJOY%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"PLAYFUL%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"PLEASANTRY%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"PLEASUR%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"PLEASURABL%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"REJOIC%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"RELIEF%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"RELIEV%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"ROLLICK%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"SATISF%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"SMIL%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"THRIL%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"THRILL%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"VIVACIOU%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"VIVACITY%" : ["SECONDARY","EMOTIONS","POSITIVE_AFFECT"],\
"TREMOR" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"AFRAID%" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"AGHAST%" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"ALARM%" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"ANGUISH%" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"ANXI%" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"AVOID%" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"BLUSH%" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"CARES" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"COWARD%" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"COWER%" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"CRISI%" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"DANGEROU%" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"DESPERAT%" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"DISTRES%" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"DREAD%" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"DREADFUL%" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"FEAR%" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"FEARFUL%" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"FRANTIC%" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"FRET%" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"FRIGHT%" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"HORRIFI%" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"HORRIFY%" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"HORROR%" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"NERVOU%" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"NERVOUSNES%" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"PANIC%" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"PHOBIA%" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"PHOBIC%" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"SCARE" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"SCARED" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"SCARES" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"SCARY" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"SHRIEK%" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"SHUDDER%" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"SHY%" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"TERRIFI%" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"TERRIFY%" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"TERROR%" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"TIMID%" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"TRAUMA%" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"TREMBL%" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"TREMULOU%" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"TROUBL%" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"UNEASINES%" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"UNEASY%" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"WORRI%" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"WORRY%" : ["SECONDARY","EMOTIONS","ANXIETY"],\
"AGGRIEVED" : ["SECONDARY","EMOTIONS","SADNESS"],\
"ALAS" : ["SECONDARY","EMOTIONS","SADNESS"],\
"DEJECT%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"DEPRES%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"DEPRESS%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"DESPAIR%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"DESPONDANT%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"DESPONDENT%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"DIRG%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"DISAPPOINT%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"DISAPPOINTMENT%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"DISCONSOLAT%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"DISCOURAG%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"DISHEARTEN%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"DISMAL%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"DISSATISFI%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"DISSATISFY%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"DISTRAUGHT%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"DOLDRUM%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"DOWNCAST%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"DREARY%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"ELEGY%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"FORLORN%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"FROWN%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"FUNEREAL%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"GRIE%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"GROAN%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"HOPELES%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"HUMILIAT%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"LAMENT%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"LAMENTAT%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"LONE%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"LONELINES%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"MELANC%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"MISERABL%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"MISERI%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"MISERY%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"MOAN%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"MOURN%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"MOURNFUL%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"ORPHAN%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"PAIN%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"PITIFUL%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"PLAINT%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"REGRET%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"REGRETFUL%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"REMORS%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"REPENT%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"REPENTANC%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"REPENTENC%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"RUE" : ["SECONDARY","EMOTIONS","SADNESS"],\
"SAD" : ["SECONDARY","EMOTIONS","SADNESS"],\
"SADDEN%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"SADLY" : ["SECONDARY","EMOTIONS","SADNESS"],\
"SADNES%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"SOB" : ["SECONDARY","EMOTIONS","SADNESS"],\
"SOBB%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"SOBS" : ["SECONDARY","EMOTIONS","SADNESS"],\
"SOMBER%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"SOMBR%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"SORROW%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"SORROWFUL%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"SORRY%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"SUFFER%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"TEARFUL%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"TRAGEDY%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"TRAGIC%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"UNHAPPINES%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"UNHAPPY%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"WAIL%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"WEEP%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"WEPT%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"WHIN%" : ["SECONDARY","EMOTIONS","SADNESS"],\
"WOE" : ["SECONDARY","EMOTIONS","SADNESS"],\
"WOES" : ["SECONDARY","EMOTIONS","SADNESS"],\
"AFFECT%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"AFFECTIONAT%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"AMOROU%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"AMOUROU%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"APPRECIAT%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"ATTRACTIV%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"BEFRIEND%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"BELOV%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"BOSOM%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"BRIDAL%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"BRIDE%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"CHERISH%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"CONGENIAL%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"CORDIAL%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"COURTSHIP%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"DARL%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"DEAR%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"DEVOT%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"EMBRAC%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"ENAMOR%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"ENAMOUR%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"ENDEAR%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"FAMILIAR%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"FONDER" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"FAREWELL%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"FAVOR%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"FAVOUR%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"FIANC%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"FLIRT%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"FOND" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"FONDNES%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"FRATERNITY%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"FRIEND%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"FRIENDSHIP%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"GOODBY%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"GRATEFUL%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"INTIMACY%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"INTIMAT%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"KIND%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"KINDNES%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"LIKE%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"LIKING%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"LOV%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"MARRI%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"MARRIAG%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"MARRY%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"MATE" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"MATED" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"MATES" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"MATING%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"MERCY%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"PAT" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"PATS" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"PATT%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"PITI%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"PITY%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"ROMANC%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"SWEETHEART%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"SYMPAT%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"UNSELFISH%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"WARMHEART%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"WELCOM%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"WOOED%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"WOOING%" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"WOOS" : ["SECONDARY","EMOTIONS","AFFECTION"],\
"ABHOR%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"ABUS%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"ABUSIV%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"ACCUS%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"AFFLICT%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"AGGRESS%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"AGGRESSIV%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"AMBUSH%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"ANGER%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"ANGRI%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"ANGRIER%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"ANGRY%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"ANNIHILAT%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"ANNOY%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"ANNOYANC%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"ANTAGONIZ%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"ARGU%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"ARGUMENT%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"ARMY%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"ARROW%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"ASSAULT%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"ATTACK%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"AVENG%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"AX" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"AXE" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"AXES" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"BATTL%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"BEAK%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"BEAT%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"BEATEN%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"BETRAY%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"BLADE%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"BLAM%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"BLOODY%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"BOTHER%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"BRAWL%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"BREAK%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"BROK%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"BROKEN%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"BRUTAL%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"CANNON%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"CHID%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"COMBAT%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"COMPLAIN%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"CONFLICT%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"CONDEMN%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"CONTROVERSY%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"CRITIC%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"CRUEL%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"CRUSH%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"CUT" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"CUTS" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"CUTT%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"DAMAG%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"DECEI%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"DEFEAT%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"DEGRAD%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"DEMOLISH%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"DEPRIV%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"DERID%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"DESPIS%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"DESTROY%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"DESTRUCT%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"DESTRUCTIV%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"DETEST%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"DISAGRE%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"DISAGREEMENT%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"DISAPPROV%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"DISCONTENT%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"DISLIK%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"DISPUT%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"DISTURB%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"DOUBT%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"ENEMI%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"ENEMY%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"ENRAG%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"EXASPERAT%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"CONTROVERSIAL%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"CRITIQUE" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"DISPARAG%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"IRRITABLE" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"EXPLOIT%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"EXTERMINAT%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"FEUD%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"FIERC%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"FIGHT%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"FOUGHT%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"FURIOU%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"FURY%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"GASH%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"GRAPPL%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"GROWL%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"GRUDG%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"GUN" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"GUNN%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"GUNS" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"HARM%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"HARSH%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"HATE%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"HATR%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"HIT" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"HITS" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"HITT%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"HOMICID%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"HOSTIL%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"HURT%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"INGRAT%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"INJUR%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"INJURY%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"INSULT%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"INVAD%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"INVAS%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"IRAT%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"IRK%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"IRRITAT%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"JEALOU%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"JEALOUSY%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"JEER%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"KICK%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"KIL%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"KILL%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"KNIF%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"KNIV%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"LOATH%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"MAIM%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"MISTREAT%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"MOCK%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"MURDER%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"OBLITERAT%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"OFFEND%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"OPPOS%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"PREDATORY%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"PROTEST%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"QUARREL%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"RAGE" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"RAGES" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"RAGING" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"RAPIN%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"REBEL%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"REBELL%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"REBUK%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"RELENTLES%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"REPROACH%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"RESENT%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"RESENTMENT%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"RETRIBUT%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"REVENG%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"REVOLT%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"RIDICUL%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"RIP" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"RIPP%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"RIPS" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"ROB" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"ROBB%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"ROBS" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"SARCASM%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"SARCASTIC%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"SCALP%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"SCOF%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"SCOFF%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"SCOURG%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"SEIZ%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"SEVER%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"SEVERITY%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"SHATTER%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"SHOOT%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"SHOT%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"SHOV%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"SLAIN%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"SLANDER%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"SLAP%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"SLAUGHTER%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"SLAY%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"SLEW%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"SMASH%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"SNARL%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"SNEER%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"SPEAR%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"SPITEFUL%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"SPURN%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"STAB%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"STEAL%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"STOL%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"STOLEN%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"STRANGL%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"STRIF%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"STRIK%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"STRUCK%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"STRUGGL%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"STUBBORN%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"SWORD%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"TAUNT%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"TEMPER%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"THREAT%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"THREATEN%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"TORE" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"TORMENT%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"TORN%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"TORTUR%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"TRAITOR%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"TRAMPL%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"TREACHEROU%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"TREACHERY%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"TYRANT%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"UNKIND%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"VENGEANC%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"VENGEFUL%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"VEX" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"VEXING" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"VIOLAT%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"VIOLENC%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"VIOLENT%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"WAR" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"WARRING" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"WARRIOR%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"WARS" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"WEAPON%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"WHIP%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"WOUND%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"WRATH%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"FOOTBALL%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"WRECK%" : ["SECONDARY","EMOTIONS","AGGRESSION"],\
"ART" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"ARTS%" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"BARD%" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"BARK%" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"BAWL%" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"BELLOW%" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"BLEAT%" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"CAROL%" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"CHANT%" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"CLOWN%" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"CRIE%" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"CRIING" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"CRY" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"DANC%" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"EXCLAIM%" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"EXPRESSIV%" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"FRISK%" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"FROLIC%" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"GAME%" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"GUITAR%" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"HARP%" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"HORN%" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"HURRAH%" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"HURRAY%" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"LULLABY%" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"LUTE" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"LUTES" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"LYRE" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"MINSTREL%" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"NEIGH" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"NEIGHS" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"PAINTER%" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"PLAY%" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"POEM%" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"POET%" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"POETIC%" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"POETRY%" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"ROAR%" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"SANG%" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"SCREAM%" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"SHOUT%" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"SIGH%" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"SING" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"SINGS%" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"SPORT%" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"SUNG%" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"TROUBADOR%" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"TROUBADOUR%" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"VIOLIN%" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"WARBL%" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"YEL%" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"YELL%" : ["SECONDARY","EMOTIONS","EXPRESSIVE_BEH"],\
"ADMIR%" : ["SECONDARY","EMOTIONS","GLORY"],\
"ADMIRABL%" : ["SECONDARY","EMOTIONS","GLORY"],\
"ADVENTUR%" : ["SECONDARY","EMOTIONS","GLORY"],\
"APPLAUD%" : ["SECONDARY","EMOTIONS","GLORY"],\
"APPLAUS%" : ["SECONDARY","EMOTIONS","GLORY"],\
"ARROGANC%" : ["SECONDARY","EMOTIONS","GLORY"],\
"ARROGANT%" : ["SECONDARY","EMOTIONS","GLORY"],\
"AUDACITY%" : ["SECONDARY","EMOTIONS","GLORY"],\
"AWE%" : ["SECONDARY","EMOTIONS","GLORY"],\
"BOAST%" : ["SECONDARY","EMOTIONS","GLORY"],\
"BOASTFUL%" : ["SECONDARY","EMOTIONS","GLORY"],\
"BRILLIANC%" : ["SECONDARY","EMOTIONS","GLORY"],\
"BRILLIANT%" : ["SECONDARY","EMOTIONS","GLORY"],\
"CAESAR%" : ["SECONDARY","EMOTIONS","GLORY"],\
"CASTL%" : ["SECONDARY","EMOTIONS","GLORY"],\
"CONQUE%" : ["SECONDARY","EMOTIONS","GLORY"],\
"CROWN%" : ["SECONDARY","EMOTIONS","GLORY"],\
"DAZZL%" : ["SECONDARY","EMOTIONS","GLORY"],\
"EAGL%" : ["SECONDARY","EMOTIONS","GLORY"],\
"ELIT%" : ["SECONDARY","EMOTIONS","GLORY"],\
"EMPEROR%" : ["SECONDARY","EMOTIONS","GLORY"],\
"EMPIR%" : ["SECONDARY","EMOTIONS","GLORY"],\
"EXALT%" : ["SECONDARY","EMOTIONS","GLORY"],\
"EXHIBIT%" : ["SECONDARY","EMOTIONS","GLORY"],\
"EXQUISIT%" : ["SECONDARY","EMOTIONS","GLORY"],\
"EXTRAORDINARY%" : ["SECONDARY","EMOTIONS","GLORY"],\
"EXTREM%" : ["SECONDARY","EMOTIONS","GLORY"],\
"FAME" : ["SECONDARY","EMOTIONS","GLORY"],\
"FAMED" : ["SECONDARY","EMOTIONS","GLORY"],\
"FAMOU%" : ["SECONDARY","EMOTIONS","GLORY"],\
"FOREMOST%" : ["SECONDARY","EMOTIONS","GLORY"],\
"GENIU%" : ["SECONDARY","EMOTIONS","GLORY"],\
"GLOR%" : ["SECONDARY","EMOTIONS","GLORY"],\
"GOLD%" : ["SECONDARY","EMOTIONS","GLORY"],\
"GOLDEN%" : ["SECONDARY","EMOTIONS","GLORY"],\
"GRANDEUR%" : ["SECONDARY","EMOTIONS","GLORY"],\
"GREAT%" : ["SECONDARY","EMOTIONS","GLORY"],\
"HAUGHTY%" : ["SECONDARY","EMOTIONS","GLORY"],\
"HERO%" : ["SECONDARY","EMOTIONS","GLORY"],\
"HOMAG%" : ["SECONDARY","EMOTIONS","GLORY"],\
"ILLUSTRIOU%" : ["SECONDARY","EMOTIONS","GLORY"],\
"KINGDOM%" : ["SECONDARY","EMOTIONS","GLORY"],\
"MAGESTIC%" : ["SECONDARY","EMOTIONS","GLORY"],\
"MAGNIFICENT%" : ["SECONDARY","EMOTIONS","GLORY"],\
"MAJESTIC%" : ["SECONDARY","EMOTIONS","GLORY"],\
"MAJESTY%" : ["SECONDARY","EMOTIONS","GLORY"],\
"NOBL%" : ["SECONDARY","EMOTIONS","GLORY"],\
"OUTSTAND%" : ["SECONDARY","EMOTIONS","GLORY"],\
"PALAC%" : ["SECONDARY","EMOTIONS","GLORY"],\
"POMP%" : ["SECONDARY","EMOTIONS","GLORY"],\
"PRESTIG%" : ["SECONDARY","EMOTIONS","GLORY"],\
"PRID%" : ["SECONDARY","EMOTIONS","GLORY"],\
"PRINC%" : ["SECONDARY","EMOTIONS","GLORY"],\
"PROUD%" : ["SECONDARY","EMOTIONS","GLORY"],\
"RENOWN%" : ["SECONDARY","EMOTIONS","GLORY"],\
"RESPLENDENT%" : ["SECONDARY","EMOTIONS","GLORY"],\
"RICH%" : ["SECONDARY","EMOTIONS","GLORY"],\
"ROYAL%" : ["SECONDARY","EMOTIONS","GLORY"],\
"ROYALTY%" : ["SECONDARY","EMOTIONS","GLORY"],\
"SCEPTR%" : ["SECONDARY","EMOTIONS","GLORY"],\
"SCORN%" : ["SECONDARY","EMOTIONS","GLORY"],\
"SPLENDID%" : ["SECONDARY","EMOTIONS","GLORY"],\
"SPLENDOR%" : ["SECONDARY","EMOTIONS","GLORY"],\
"STRUT%" : ["SECONDARY","EMOTIONS","GLORY"],\
"SUBLIM%" : ["SECONDARY","EMOTIONS","GLORY"],\
"SUPERIOR%" : ["SECONDARY","EMOTIONS","GLORY"],\
"SUPERIORITY%" : ["SECONDARY","EMOTIONS","GLORY"],\
"SUPREM%" : ["SECONDARY","EMOTIONS","GLORY"],\
"THRON%" : ["SECONDARY","EMOTIONS","GLORY"],\
"TRIUMP%" : ["SECONDARY","EMOTIONS","GLORY"],\
"VICTOR%" : ["SECONDARY","EMOTIONS","GLORY"],\
"VICTORIOU%" : ["SECONDARY","EMOTIONS","GLORY"],\
"VICTORY%" : ["SECONDARY","EMOTIONS","GLORY"],\
"WEALTH%" : ["SECONDARY","EMOTIONS","GLORY"],\
"WONDER%" : ["SECONDARY","EMOTIONS","GLORY"],\
"WONDERFUL%" : ["SECONDARY","EMOTIONS","GLORY"]\
}';

var RID = $.parseJSON(json);


var primaryCats = {
	NEED:["ORALITY","ANALITY","SEX"],
	SENSATION:["TOUCH","TASTE","ODOR","GEN_SENSATION","SOUND","VISION","COLD","HARD","SOFT"],
	DEFENSIVE_SYMBOL:["PASSIVITY","VOYAGE","RANDOM MOVEMENT","DIFFUSION","CHAOS"],
	REGR_KNOL:["UNKNOW","TIMELESSNES","COUNSCIOUS","BRINK-PASSAGE","NARCISSISM","CONCRETENESS"],
	ICARIAN_IM:["ASCEND","HEIGHT","DESCENT","DEPTH","FIRE","WATER"]
};
var secondaryCats = {
	NONEMOTION:["ABSTRACT_TOUGHT","SOCIAL_BEHAVIOR","INSTRU_BEHAVIOR","RESTRAINT","ORDER","TEMPORAL_REPERE","MORAL_IMPERATIVE"],
	EMOTIONS:["POSITIVE_AFFECT","ANXIETY","SADNESS","AFFECTION","AGGRESSION","EXPRESSIVE_BEH","GLORY"]
};
var categories = {
	PRIMARY:primaryCats,
	SECONDARY:secondaryCats
};

function wordCounts(str){
	str = str.replace(/[^\w\s]|_/g, "").toUpperCase();
	words = str.split(/\s+/g);
	var catCount = {};
	for (word in words){
		var wordData = getCategories(words[word]);
		if (wordData){
			for (category in wordData){
				if (catCount[wordData[category]] == undefined){
					catCount[wordData[category]] = 0;
				}
				catCount[wordData[category]]++;
			}
		}
	}
	return catCount;
}

function getEmotionData(str){
	counts = wordCounts(str);
	var outCounts = {};
	var emotions = categories["SECONDARY"]["EMOTIONS"];
	for(var i = 0; i < emotions.length; i++){
		var emotion = emotions[i];
		if (counts[emotion]){
			outCounts[emotion]=counts[emotion];
		}
		else{
			outCounts[emotion]=0;
		}
	}
	return outCounts;
}

//returns map of categories if word is found and not in exclude
// map keys are (cat,subcat,subsubcat)
// else returns null
function getCategories(word){
	while(word.length > 0){
		if (RID[word]){
			return RID[word];
		}
		if (RID[word+"%"]){
			return RID[word+"%"];
		}
		word = String(word).substr(0,word.length-1);
	}
	return null;
}

function analyze() {
	cats = ["POSITIVE_AFFECT", "ANXIETY", "SADNESS", "AFFECTION", "AGGRESSION", "EXPRESSIVE_BEH", "GLORY"]
	ta = document.getElementById("textarea");
	var text = ta.value;
	if(text.length < 1) return;
	dataLabelDict = getEmotionData(text);
	var chart = new AwesomeChart('popupChartCanvas');
	chart.chartType = "pie";
	//chart.title = "Worldwide browser market share: December 2010";
	chart.data = [];
	chart.labels = [];
	for(var emotion in dataLabelDict){
	if(dataLabelDict[emotion] != 0){
	//alert('label: '+emotion+' | number: '+dataLabelDict[emotion]);
	  chart.labels.push(emotion);
	  chart.data.push(dataLabelDict[emotion]);
	}
	}
	chart.colors = ['#006CFF', '#FF6600', '#34A038', '#945D59', '#93BBF4', '#F493B8'];
	chart.draw();
}